#server:
#  port: 9090
#spring:
#  application:
#    name: mayikt-weixin
#  cloud:
#    nacos:
#      discovery:
#        ##nacos服务注册地址
#        server-addr: 122.51.108.102:8849
#
#swagger:
#  base-package: com.mayikt.weixin.impl.service
#  title: SpringCloud2.x构建微服务电商项目-微信服务接口
#  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
#  version: 1.1
#  terms-of-service-url: www.mayikt.com
#  contact:
#    name: 97后互联网架构师-余胜军
#    email: 644064779@qq.com
#    url: www.mayikt.com
#  enabled: true

mayikt:
  wx:
    defaultMsg:  您的消息我已经收到了，后期会给您回复的噢!
    rpcWeatherUrl: https://api.seniverse.com/v3/weather/now.json?key=S2f6L62SpD0ivVO6j&location=####&language=zh-Hans&unit=c
